services:
  alfresco:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.alfresco.rule=PathPrefix(`/alfresco`)"
      - "traefik.http.routers.alfresco.priority=100"
      - "traefik.http.services.alfresco.loadbalancer.server.port=8080"
      - "traefik.http.middlewares.alfresco-root-redirect.redirectregex.regex=^https?://[^/]+/([^/.]+)$$"
      - "traefik.http.middlewares.alfresco-root-redirect.redirectregex.replacement=$$0/"
      - "traefik.http.middlewares.alfresco-chain.chain.middlewares=alfresco-root-redirect@docker"
      - "traefik.http.routers.alfresco.middlewares=alfresco-chain@docker"
      - "traefik.http.routers.solrapideny.rule=PathRegexp(`^/alfresco/(wc)?s(ervice)?/api/solr/.*$$`)"
      - "traefik.http.middlewares.acsfakeauth.basicauth.users=fake:"
      - "traefik.http.routers.solrapideny.middlewares=acsfakeauth@docker"
      - "traefik.http.routers.alfrescomicrometer.rule=PathRegexp(`^/alfresco/(wc)?s(ervice)?/prometheus`)"
      - "traefik.http.middlewares.prometheusipfilter.ipallowlist.sourcerange=127.0.0.0/8"
      - "traefik.http.routers.alfrescomicrometer.middlewares=prometheusipfilter@docker"
  share:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.share.rule=PathPrefix(`/share`)"
      - "traefik.http.routers.share.priority=100"
      - "traefik.http.services.share.loadbalancer.server.port=8080"
      - "traefik.http.middlewares.share-limit.buffering.maxRequestBodyBytes=5368709120"
      - "traefik.http.middlewares.share-root-redirect.redirectregex.regex=/share$$"
      - "traefik.http.middlewares.share-root-redirect.redirectregex.replacement=/share/"
      - "traefik.http.middlewares.share-chain.chain.middlewares=share-root-redirect@docker,share-limit@docker"
      - "traefik.http.routers.share.middlewares=share-chain@docker"
      - "traefik.http.routers.proxiedsolrapideny.rule=PathRegexp(`^/share/proxy/alfresco(-(noauth|feed|api))?/api/solr/`)"
      - "traefik.http.middlewares.sharefakeauth.basicauth.users=fake:"
      - "traefik.http.routers.proxiedsolrapideny.middlewares=sharefakeauth@docker"
  content-app:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.aca.rule=PathPrefix(`/`)"
      - "traefik.http.routers.aca.priority=1"
      - "traefik.http.services.content-app.loadbalancer.server.port=8080"
  oop-extension:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.oop-extension.rule=PathPrefix(`/alfresco-oop`)"
      - "traefik.http.routers.oop-extension.priority=200"
      - "traefik.http.services.oop-extension.loadbalancer.server.port=8081"
      - "traefik.http.middlewares.oop-extension-stripprefix.stripprefix.prefixes=/alfresco-oop"
      - "traefik.http.routers.oop-extension.middlewares=oop-extension-stripprefix@docker"
  proxy:
    image: traefik:3.1
    mem_limit: 256MB
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:8080"
      - "--entrypoints.web.transport.respondingTimeouts.readTimeout=20m"
      - "--entrypoints.web.transport.respondingTimeouts.writeTimeout=20m"
      - "--entrypoints.web.transport.respondingTimeouts.idleTimeout=20m"
      - "--entryPoints.traefik.address=:8888"
      - "--accesslog=true"
      - "--providers.docker.exposedByDefault=false"
      - "--ping.entrypoint=web"
      - "--ping=true"
    ports:
      - "8080:8080"
      - "8888:8888"
    healthcheck:
      test: ["CMD", "traefik", "healthcheck", "--ping"]
      interval: 20s
      timeout: 10s
      retries: 3
      start_period: 10s
    security_opt:
      - label=disable # Required for accessing the Docker socket on Selinux enabled systems
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
